### ISSUE TITLE
Adding erosion / dilation / opening / closing

### ISSUE THREAD

**Issue by K-Meech** [haesleinhuepf/napari-segment-blobs-and-things-with-membranes#32]
It would be useful to add scikit-image's erosion / dilation / opening / closing functions from `skimage.morphology`

I'd be happy to put together a PR adding this - if you think it's a useful addition?

**Comment by haesleinhuepf** [comment]
Hi @K-Meech ,

yes, that sounds like a useful extension! You can use these functions as blueprints as they are quite similar:

https://github.com/haesleinhuepf/napari-segment-blobs-and-things-with-membranes/blob/2f04ac40383ff1c7df390e21975584f6dad64c11/napari_segment_blobs_and_things_with_membranes/__init__.py#L448-L455

https://github.com/haesleinhuepf/napari-segment-blobs-and-things-with-membranes/blob/2f04ac40383ff1c7df390e21975584f6dad64c11/napari_segment_blobs_and_things_with_membranes/__init__.py#L382-L391

Thanks for considering investing time here! 🙏

Best,
Robert
