### ISSUE TITLE
error running Manually merge labels/split labels

### ISSUE THREAD

**Issue by chili-chiu** [haesleinhuepf/napari-segment-blobs-and-things-with-membranes#7]
Environment:
napari 0.4.15
Plugins:
- clEsperanto: 0.16.0
- console: 0.0.4
- napari-assistant: 0.1.6
- napari-segment-blobs-and-things-with-membranes: 0.2.20
- napari-time-slicer: 0.4.3
- napari_skimage_regionprops1: 0.3.2
- napari_skimage_regionprops2: 0.3.2
- scikit-image: 0.4.15
- svg: 0.1.6

Steps to reproduce:
(1) File > Open Sample > napari > Cell
(2) pyClEsperanto > Label > use default
(3.1) create a points layer, manually place two points on different labels
(4.1) nsbatwm > manually merge labels --> AttributeError: 'OCLArray' object has no attribute 'item'

(3.2) create a points layer, manually place two points within the same label
(4.2) nsbatwm > manually split labels --> AttributeError: 'OCLArray' object has no attribute 'item'

**Comment by haesleinhuepf** [comment]
Hi @chili-chiu ,

thanks for reporting! I just fixed this in napari-segment-blobs-and-things-with-membranes 0.2.21. Would you mind updating your installation and confirming that it works now for you?

Thanks again!

Best,
Robert

**Comment by chili-chiu** [comment]
just tested and it works! thanks for the speedy fix @haesleinhuepf!
